export const products = [
  // --- دسته‌بندی اول: الکترونیک و گجت‌ها (وسایل الکترونیکی) ---
  {
    id: 1,
    title: "گوشی سامسونگ S23 Ultra",
    price: 65000000,
    rate: 4.8,
    special: true,
    description:
      "نمایشگر خیره کننده و دوربین ۲۰۰ مگاپیکسلی با پشتیبانی از قلم S-Pen",
    image: "/images/s23.png",
    category: "وسایل الکترونیکی",
  },
  {
    id: 2,
    title: "آیفون ۱۵ پرو مکس",
    price: 82000000,
    rate: 4.9,
    special: true,
    description: "تراشه A17 Pro با بدنه تیتانیوم و دوربینهای فوق پیشرفته",
    image: "/images/iphone15.png",
    category: "وسایل الکترونیکی",
  },
  {
    id: 3,
    title: "لپ تاپ مک بوک ایر M2",
    price: 45000000,
    rate: 4.7,
    special: false,
    description:
      "بهترین انتخاب برای برنامه‌نویسان و گرافیک با باتری فوق العاده",
    image: "/images/macbook.png",
    category: "لپتاپ",
  },
  {
    id: 4,
    title: "ساعت اپل سری ۹",
    price: 18000000,
    rate: 4.5,
    special: false,
    description: "پایش دقیق سلامتی و ورزش با نمایشگر همیشه روشن",
    image: "/images/applewatch.png",
    category: "ساعت",
  },
  {
    id: 5,
    title: "هدفون l-sonic Noise Cancelling",
    price: 12000000,
    rate: 4.3,
    special: false,
    description: "حذف نویز محیطی با کیفیت صدای استودیویی",
    image: "/images/headphone3.png",
    category: "هدفون",
  },
  {
    id: 6,
    title: "تبلت شیائومی پد ۶",
    price: 15000000,
    rate: 4.4,
    special: false,
    description: "نمایشگر ۱۴۴ هرتزی برای تماشای فیلم و کارهای دانشجویی",
    image: "/images/xiaomi-pad.png",
    category: "تبلت",
  },
  {
    id: 7,
    title: "ایرپاد پرو نسل ۲",
    price: 9000000,
    rate: 4.6,
    special: false,
    description: "صدای فراگیر و اتصال سریع به تمام دستگاه‌های اپل",
    image: "/images/airpods.png",
    category: "وسایل الکترونیکی",
  },
  {
    id: 8,
    title: "کنسول بازی سونی PS5",
    price: 28000000,
    rate: 4.9,
    special: true,
    description: "تجربه نسل جدید بازی‌ها با سرعت لود فوق سریع SSD",
    image: "/images/ps5.png",
    category: "وسایل الکترونیکی",
  },
  {
    id: 9,
    title: "ماوس گیمینگ لوگیتک G502",
    price: 4500000,
    rate: 4.7,
    special: true,
    description: "دقت بالا و دکمه‌های قابل شخصی‌سازی برای گیمرهای حرفه‌ای",
    image: "/images/mouse3.png",
    category: "موس",
  },
  {
    id: 10,
    title: "پاوربانک ۲۰۰۰۰ مدل FastCharge",
    price: 2500000,
    rate: 4.1,
    special: false,
    description: "شارژ سریع ۲۲.۵ وات با ظرفیت واقعی و بدنه مقاوم",
    image: "/images/powerbank3.png",
    category: "پاوربانک",
  },

  // --- دسته‌بندی دوم: مد و پوشاک (فشن) ---
  {
    id: 11,
    title: "تیشرت پنبه‌ای مدل کژوال",
    price: 450000,
    rate: 4.2,
    special: false,
    description: "جنس ۱۰۰ درصد پنبه با قابلیت ضد چروک و رنگ ثابت",
    image: "/images/tshirt.png",
    category: "فشن",
  },
  {
    id: 12,
    title: "شلوار جین مدل اسلیم فیت",

    price: 1200000,
    rate: 4.5,
    special: false,
    description: "جین با کیفیت درجه یک با برش استاندارد و دوخت مقاوم",
    image: "/images/jeans.png",
    category: "فشن",
  },
  {
    id: 13,
    title: "کفش کتانی مدل اسنیکرز",
    price: 2800000,
    rate: 4.6,
    special: false,
    description: "کفی طبی و راحت برای استفاده روزمره و پیاده‌روی",
    image: "/images/sneakers.png",
    category: "فشن",
  },
  {
    id: 14,
    title: "جا کت چرمی اصل",
    price: 5500000,
    rate: 4.8,
    special: true,
    description: "چرم طبیعی گاو با کیفیت صادراتی و زیپ‌های YKK",
    image: "/images/leather-jacket.png",
    category: "فشن",
  },
  {
    id: 15,
    title: "پیراهن رسمی مردانه",
    price: 900000,
    rate: 4.3,
    special: false,
    description: "پارچه تایلندی با تراکم بالا، مناسب برای مراسم‌های رسمی",
    image: "/images/shirt.png",
    category: "فشن",
  },
  {
    id: 16,
    title: "ساعت مچی استیل مدل کلاسیک",
    price: 3200000,
    rate: 4.7,
    special: true,
    description: "مقاوم در برابر آب تا ۵۰ متر با شیشه ضد خش",
    image: "/images/watch3.png",
    category: "ساعت",
  },
  {
    id: 17,
    title: "عینک آفتابی مدل پلاریزه",
    price: 1100000,
    rate: 4.1,
    special: false,
    description: "محافظت کامل در برابر اشعه UV با طراحی مدرن",
    image: "/images/sunglasses.png",
    category: "فشن",
  },
  {
    id: 18,
    title: "کیف دستی چرمی زنانه",
    price: 2200000,
    rate: 4.4,
    special: false,
    description: "طراحی مینیمال با فضای داخلی کاربردی و کیفیت عالی",
    image: "/images/handbag.png",
    category: "فشن",
  },
  {
    id: 19,
    title: "کلاه‌ شب مدل بیس‌بال",
    price: 300000,
    rate: 3.9,
    special: false,
    description: "پارچه خنک و مناسب برای تابستان با قابلیت تنظیم سایز",
    image: "/images/cap.png",
    category: "فشن",
  },
  {
    id: 20,
    title: "هودی مدل اورسایز",
    price: 1400000,
    rate: 4.6,
    special: false,
    description: "پارچه دو لایه گرم با کلاه قابل تنظیم و کیفیت بالای چاپ",
    image: "/images/hoodie.png",
    category: "فشن",
  },

  // --- دسته‌بندی سوم: خانه و آشپزخانه (خانه و کاشانه) ---
  {
    id: 21,
    title: "سرخ‌کن بدون روغن فیلیپس",
    price: 14000000,
    rate: 4.8,
    special: true,
    description: "پخت غذا با کمترین میزان روغن و حفظ ویتامین‌ها",
    image: "/images/airfryer.png",
    category: "خانه و کاشانه",
  },
  {
    id: 22,
    title: "ماشین اسپرسو مدل Beko",
    price: 11000000,
    rate: 4.5,
    special: false,
    description: "استخراج عصاره غلیظ قهوه با نازل بخار برای کف شیر",
    image: "/images/coffee-machine.png",
    category: "خانه و کاشانه",
  },
  {
    id: 23,
    title: "جارو برقی رباتیک مدل Xiaomi",
    price: 16000000,
    rate: 4.7,
    special: true,
    description: "تمیز کردن خودکار محیط با قابلیت نقشه‌برداری از خانه",
    image: "/images/robot-vacuum.png",
    category: "خانه و کاشانه",
  },
  {
    id: 24,
    title: "بلندر و مخلوط‌کن مدل مولینکس",
    price: 4200000,
    rate: 4.3,
    special: false,
    description: "تیغه‌های استیل ضد زنگ با قدرت موتور بالا برای یخ",
    image: "/images/blender.png",
    category: "خانه و کاشانه",
  },
  {
    id: 25,
    title: "توستر مدل دو تکه",
    price: 2100000,
    rate: 4.0,
    special: false,

    description: "تنظیم میزان برشته شدن نان با تایمر دقیق",
    image: "/images/toaster.png",
    category: "خانه و کاشانه",
  },
  {
    id: 26,
    title: "تصفیه هوا مدل Sharp",
    price: 9500000,
    rate: 3.6,
    special: false,
    description: "حذف گرد و غبار و باکتری‌ها با فیلتر HEPA پیشرفته",
    image: "/images/air-purifier.png",
    category: "خانه و کاشانه",
  },
  {
    id: 27,
    title: "ست ظروف چینی مدل لوکس",
    price: 7800000,
    rate: 4.8,
    special: true,
    description: "طراحی کلاسیک با لعاب درخشان، مناسب برای پذیرایی",
    image: "/images/dinnerware.png",
    category: "خانه و کاشانه",
  },
  {
    id: 28,
    title: "لامپ هوشمند RGB",
    price: 600000,
    rate: 4.2,
    special: false,
    description: "تغییر رنگ از طریق اپلیکیشن و کنترل صوتی",
    image: "/images/smart-bulb.png",
    category: "خانه و کاشانه",
  },
  {
    id: 29,
    title: "کتری برقی مدل مدل استیل",
    price: 2800000,
    rate: 4.4,
    special: true,
    description: "جوش آوردن سریع آب با سیستم قطع‌کن خودکار",
    image: "/images/kettle.png",
    category: "خانه و کاشانه",
  },
  {
    id: 30,
    title: "میکروویو مدل LG",
    price: 13000000,
    rate: 4.7,
    special: true,
    description: "گرم کردن سریع غذا با توابع پخت متنوع و بهداشتی",
    image: "/images/microwave.png",
    category: "خانه و کاشانه",
  },
  {
    id: 31,
    title: "لپ‌تاپ فوق سریع مدل Nova-X",
    price: 110000000,
    rate: 3.9,
    special: false,
    image: "/images/laptop.png",
    description:
      "با بهره‌ گیری از جدیدترین تکنولوژی‌های روز، این محصول ترکیبی عالی از سرعت، دقت و کارایی را در اختیار شما می‌گذارد.",
    category: "لپتاپ",
  },
  {
    id: 32,
    title: "اسپیکر قابل حمل مدل Air-Beat",
    price: "1250000",
    rate: 3.9,
    special: false,
    image: "/images/speaker.png",
    description:
      "تعادل کامل بین وزن سبک و قدرت بالا؛ محصولی ایده‌آل برای افرادی که همیشه در حرکت هستند و به جابه‌جایی آسان نیاز دارند.",
    category: "بلندگو",
  },
  {
    id: 33,
    title: "هدفون بی‌سیم مدل Base-Sound (نسخه اقتصادی)",
    price: 1700000,
    rate: 3.9,
    special: false,
    image: "/images/headphone.png",
    description:
      "اقتصادی‌ترین انتخاب با حفظ بالاترین استانداردهای کیفی، مخصوص مشتریانی که به دنبال ارزش خرید بالا در برابر قیمت هستند.",
    category: "هدفون",
  },
  {
    id: 34,
    title: "مانیتور گیمینگ سری Ultra-View 4K",
    price: "52000000",
    rate: 3.9,
    special: false,
    image: "/images/monitor.png",
    description:
      "نسخه‌ی حرفه‌ای و ارتقا یافته با قابلیت‌های اختصاصی، مناسب برای کاربرانی که به دنبال بهترینِ بهترین‌ها در بازار هستند.",
    category: "مانیتور",
  },
  {
    id: 35,
    title: "مانیتور گیمینگ سری Ultra-View 4K",
    price: "52000000",
    rate: 5.0,
    special: true,
    image: "/images/monitor.png",
    description:
      "نسخه‌ی حرفه‌ای و ارتقا یافته با قابلیت‌های اختصاصی، مناسب برای کاربرانی که به دنبال بهترینِ بهترین‌ها در بازار هستند.",
    category: "مانیتور",
  },
  {
    id: 36,
    title: "ماوس گیمینگ مدل Swift-Click",
    price: "700000",
    rate: 3.9,
    special: false,
    image: "/images/mouse2.png",
    description:
      "سرعت پاسخ‌دهی فوق‌العاده و سنسور دقیق برای گیمرهای حرفه‌ای و رقابتی.",
    category: "موس",
  },
  {
    id: 37,
    title: "لپ‌تاپ مهندسی مدل Zenith-Book",
    price: "98000000",
    rate: 4.0,
    special: true,
    image: "/images/laptop2.png",
    description:
      "قدرت پردازش بی‌نظیر برای کارهای گرافیکی، رندرینگ و برنامه‌نویسی سنگین",
    category: "لپتاپ",
  },
  {
    id: 38,
    title: "شارژر سریع مدل Volt-Core",
    price: "4900000",
    rate: 4.7,
    special: true,
    image: "/images/powerbank2.png",
    description:
      "ظرفیت بالا و تکنولوژی شارژ سریع برای تغذیه چندین دستگاه در یک زمان",
    category: "پاوربانک",
  },
  {
    id: 39,
    title: "اسپیکر بیس‌دار مدل Bass-Boom",
    price: "3200000",
    rate: 2.9,
    special: false,
    image: "/images/speaker2.png",
    description:
      "صدای عمیق و لرزاننده با طراحی مقاوم در برابر آب و ضربه برای محیط‌های باز",
    category: "بلندگو",
  },
  {
    id: 40,
    title: "چراغ هوشمند مدل Luna-Glow",
    price: "600000",
    rate: 4.5,
    special: true,
    image: "/images/lamp2.png",
    description:
      "کنترل از راه دور با اپلیکیشن و طیف رنگی متنوع برای هر فضای کاری",
    category: "چراغ مطالعه",
  },
  {
    id: 41,
    title: "هدفون حذف نویز مدل Pure-Silence",
    price: "1500000",
    rate: 1.9,
    special: false,
    image: "/images/headphone2.png",
    description: "تجربه صدای کریستالی با حذف کامل محیط اطراف و کیفیت استودیویی",
    category: "هدفون",
  },
  {
    id: 42,
    title: "ساعت ورزشی مدل Active-Track",
    price: "2200000",
    rate: 3.5,
    special: false,
    image: "/images/watch2.png",
    description:
      "ایده‌آل برای ورزشکاران با قابلیت‌های پیشرفته پایش سلامت و گام‌شمار دقیق",
    category: "ساعت",
  },
  {
    id: 43,
    title: "مانیتور فوق‌عریض مدل Horizon-Curve",
    price: "39000000",
    rate: 3.1,
    special: false,
    image: "/images/monitor2.png",
    description:
      "زاویه دید گسترده و رزولوشن خیره‌کننده برای غرق شدن در دنیای بازی و سینما",
    category: "مانیتور",
  },
  {
    id: 44,
    title: "Mouse_Pro Comfort model",
    price: 450000,
    rate: 4.9,
    special: true,
    image: "/images/mouse.png",
    description:
      "موس دو کلیده با کارکردی  راحت برای کاربر گرامی  - به همراه نور درونی 8 رنگه ",
    category: "موس",
  },
  {
    id: 45,
    title: "Titan-Power PowerBank Super fast charging",
    price: 4700000,
    rate: 3.2,
    special: false,
    image: "/images/powerbank.png",
    description:
      "این پاور بانک با قدرت خارق االعاده 60 وات شارژ گوشی شما رو با سرعت باورنکردنی و به طور ایمن شارژ میکند که با حجم 20.000 آمپری خودش قابلیت شارژ حداق 4 گوشی رو دارد که برای سفرهای طولانی یک همسفر ایمن و مطمين به شمار می آید.",
    category: "پاوربانک",
  },
  {
    id: 46,
    title: "HQ-90 Smart watch - ساعت هوشمند",
    price: 2800000,
    rate: 3.9,
    special: false,
    image: "/images/watch.png",
    description:
      " ساعت هوشمند با قابلیت  تتعیین نبض و ضربان قبل - محاسبه تعداد قدم ها و همچنین فیلمبرداری بع وعکس به طور سلفی و اینکه مهم ترنی قابلیت این ساعت هوشمند  توانایی اتصال بع اینترنت و استفاده از  پیامرسان ها میباشد ",
    category: "ساعت",
  },
];
