export const dynamic = "force-dynamic";

import Sidebar from "../components/SideBar";
import "../styles/globals.css";

export const metadata = {
  title: "Digi Admin",
  description: "Generated by next1 Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-amber-100">
      <body>
        <main className="flex">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
