export const dynamic = "force-dynamic";
export const revalidate = 0;

import ToggleAlert from "../components/effects/alert";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Providers from "../components/Provider";
import CartProvider from "../Contexts/CartContext";
import "../styles/globals.css";
export const metadata = {
  title: "MaxBax",
  description: "Generated by Next1 Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <Providers>
          <Header />
          {children}
          <ToggleAlert />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
