export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

import ToggleAlert from "../components/effects/alert";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Providers from "../components/Provider";
import CartProvider from "../Contexts/CartContext";
import "../styles/globals.css";
export const metadata = {
  title: "MaxBax",
  description: "Generated by Next1 Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <Providers>
          <CartProvider>
            <Header />
            {children}
            <ToggleAlert />
            <Footer />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
